name: "WePower Sensor"
slug: "wepower_iot"
description: "Enhanced multi-serial scanner with device type detection, MQTT queuing, and two-way communication"
version: "0.2.0"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - share:rw
options:
  mqtt_broker: "mqtt://homeassistant:1883"
  mqtt_username: ""
  mqtt_password: ""
  scan_interval: 0.02
  include_patterns:
    - "/dev/ttyUSB*"
    - "/dev/ttyACM*"
  exclude_patterns:
    - "/dev/ttyS*"
    - "/dev/input*"
    - "/dev/hidraw*"
  enable_discovery: true
  discovery_prefix: "homeassistant"
  probe_command: ""
  # Enhanced settings for Phase 2
  device_timeout: 30.0
  retry_attempts: 3
  retry_delay: 1.0
  message_queue_size: 100
  enable_device_detection: true
  identification_timeout: 5.0
  # Device identification commands
  ble_identification_cmd: "AT+BLEINFO\r\n"
  zigbee_identification_cmd: "AT+ZIGINFO\r\n"
  generic_identification_cmd: "AT+INFO\r\n"
  # Phase 2 enhanced settings
  enable_device_pairing: true
  pairing_timeout: 30.0
  heartbeat_interval: 10.0
  connection_quality_threshold: 0.8
  enable_device_management: true
  device_management_port: 8080
  max_paired_devices: 50
  # Client requirements
  enable_ble_pairing: true
  enable_zigbee_pairing: true
  ble_manual_input_enabled: true
  ble_network_key_exchange: false
schema:
  mqtt_broker: str
  mqtt_username: str?
  mqtt_password: str?
  scan_interval: float
  include_patterns:
    - str
  exclude_patterns:
    - str
  enable_discovery: bool
  discovery_prefix: str
  probe_command: str?
  # Enhanced schema for Phase 2
  device_timeout: float?
  retry_attempts: int?
  retry_delay: float?
  message_queue_size: int?
  enable_device_detection: bool?
  identification_timeout: float?
  # Device identification commands schema
  ble_identification_cmd: str?
  zigbee_identification_cmd: str?
  generic_identification_cmd: str?
  # Phase 2 enhanced settings schema
  enable_device_pairing: bool?
  pairing_timeout: float?
  heartbeat_interval: float?
  connection_quality_threshold: float?
  enable_device_management: bool?
  device_management_port: int?
  max_paired_devices: int?
  # Client requirements schema
  enable_ble_pairing: bool?
  enable_zigbee_pairing: bool?
  ble_manual_input_enabled: bool?
  ble_network_key_exchange: bool?
